spring:
  application:
    name: User Service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:myuser}
    password: ${DB_PASS:mypassword}
    driver-class-name: org.postgresql.Driver

server:
  port: 8081
  # Enable SSL
  ssl:
    # Client Keystore - contains gateway's certificate
    key-store: classpath:ssl/user-keystore.p12
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    # Truststore - contains CA cert to trust UserService
    trust-store: classpath:ssl/user-truststore.jks
    trust-store-password: changeit
    trust-store-type: JKS
    # Enforce client authentication - mTLS
    client-auth: need
    enabled: true